# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10RRdh0eNwnaMapoP2V0xGkLrg_VZCPDV
"""

print('hello')

from typing import OrderedDict
number=[]
for i in range(7):
     num=int(input("enter a number:"))
     number.append(num)
largest=max(number)
smallest=min(number)
total=sum(number)
even_count=0
odd_count=0
for num in number:
    if num % 2 == 0:
        even_count +=1
    else:
      odd_count +=1
print("numbers:", number)
print("largest numbers:",largest)
print("smallest number:", smallest)
print("sum of the number:",total)
print("Even numbers count:", even_count)
print("odd numbers count:",odd_count)

marks=[]
for i in range(3):
  mark=int(input("enter Mark:"))
  marks.append(mark)
highest=max(marks)
lowest=min(marks)
avarage=sum(marks)
passed=0
failed=0
for mark in marks:
  if mark>=40:
    passed +=1
  else:
    failed +=1
print("marks:",marks)
print("highest marks:", highest)
print("lowest marks:", lowest)
print("average marks:",avarage)
print("passed students:",passed)
print("failed students:",failed)